url: https://joeennever.github.io
baseurl: /

# Site settings
title: Tiina Ennever
email: contact@tiinaennever.design
description: "Tiina Ennever's Portfolio."

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/tiina-ennever/

# Postal address (add as many lines as necessary)
address:
  - line: Helsinki, Finland

# Build settings
markdown: kramdown
permalink: pretty
